import {
  Campaign,
  Channel,
  ContentAsset,
  AttributionModel,
  AIGeneratedContent,
  MarketingMetrics,
} from "./types";

export const channels: Channel[] = [
  {
    id: "ch-email",
    name: "Email Marketing",
    type: "email",
    budget: 85000,
    spend: 78200,
    impressions: 2450000,
    clicks: 183750,
    conversions: 14700,
    roas: 4.2,
    cpa: 5.32,
    ctr: 7.5,
    revenue: 328440,
  },
  {
    id: "ch-social",
    name: "Social Media",
    type: "social",
    budget: 120000,
    spend: 114500,
    impressions: 8900000,
    clicks: 445000,
    conversions: 8900,
    roas: 2.8,
    cpa: 12.87,
    ctr: 5.0,
    revenue: 320600,
  },
  {
    id: "ch-search",
    name: "Paid Search",
    type: "search",
    budget: 200000,
    spend: 187300,
    impressions: 4200000,
    clicks: 630000,
    conversions: 25200,
    roas: 3.5,
    cpa: 7.43,
    ctr: 15.0,
    revenue: 655550,
  },
  {
    id: "ch-display",
    name: "Display Advertising",
    type: "display",
    budget: 75000,
    spend: 68900,
    impressions: 12500000,
    clicks: 187500,
    conversions: 3750,
    roas: 1.9,
    cpa: 18.37,
    ctr: 1.5,
    revenue: 130910,
  },
  {
    id: "ch-content",
    name: "Content Marketing",
    type: "content",
    budget: 60000,
    spend: 54800,
    impressions: 1800000,
    clicks: 162000,
    conversions: 6480,
    roas: 5.1,
    cpa: 8.46,
    ctr: 9.0,
    revenue: 279480,
  },
];

export const contentAssets: ContentAsset[] = [
  {
    id: "asset-1",
    campaignId: "camp-1",
    title: "Q3 Product Launch Landing Page",
    type: "landing_page",
    channel: "search",
    aiScore: 92,
    status: "published",
    performance: { impressions: 45000, clicks: 6750, conversions: 540, engagement: 8.2 },
    createdAt: "2026-05-01T08:00:00Z",
    updatedAt: "2026-06-08T14:30:00Z",
  },
  {
    id: "asset-2",
    campaignId: "camp-1",
    title: "Product Demo Video Script",
    type: "video_script",
    channel: "social",
    aiScore: 88,
    status: "approved",
    performance: { impressions: 32000, clicks: 4800, conversions: 384, engagement: 7.8 },
    createdAt: "2026-05-10T10:00:00Z",
    updatedAt: "2026-06-07T09:15:00Z",
  },
  {
    id: "asset-3",
    campaignId: "camp-2",
    title: "Summer Sale Email Sequence",
    type: "email_campaign",
    channel: "email",
    aiScore: 95,
    status: "published",
    performance: { impressions: 180000, clicks: 16200, conversions: 2430, engagement: 9.1 },
    createdAt: "2026-06-01T06:00:00Z",
    updatedAt: "2026-06-09T08:00:00Z",
  },
  {
    id: "asset-4",
    campaignId: "camp-2",
    title: "Retargeting Display Banner Set",
    type: "ad_copy",
    channel: "display",
    aiScore: 78,
    status: "published",
    performance: { impressions: 520000, clicks: 7800, conversions: 312, engagement: 3.4 },
    createdAt: "2026-06-01T06:00:00Z",
    updatedAt: "2026-06-08T16:00:00Z",
  },
  {
    id: "asset-5",
    campaignId: "camp-3",
    title: "Enterprise ROI Whitepaper",
    type: "blog",
    channel: "content",
    aiScore: 91,
    status: "published",
    performance: { impressions: 28000, clicks: 3920, conversions: 470, engagement: 12.5 },
    createdAt: "2026-04-15T09:00:00Z",
    updatedAt: "2026-06-05T11:00:00Z",
  },
  {
    id: "asset-6",
    campaignId: "camp-3",
    title: "LinkedIn Thought Leadership Post",
    type: "social_post",
    channel: "social",
    aiScore: 85,
    status: "published",
    performance: { impressions: 95000, clicks: 7600, conversions: 380, engagement: 6.2 },
    createdAt: "2026-05-20T12:00:00Z",
    updatedAt: "2026-06-06T10:30:00Z",
  },
  {
    id: "asset-7",
    campaignId: "camp-4",
    title: "Holiday Gift Guide Blog Post",
    type: "blog",
    channel: "content",
    aiScore: 89,
    status: "published",
    performance: { impressions: 42000, clicks: 6300, conversions: 756, engagement: 10.1 },
    createdAt: "2026-05-25T08:00:00Z",
    updatedAt: "2026-06-07T15:45:00Z",
  },
  {
    id: "asset-8",
    campaignId: "camp-4",
    title: "Instagram Story Ad Series",
    type: "ad_copy",
    channel: "social",
    aiScore: 82,
    status: "review",
    performance: { impressions: 180000, clicks: 9000, conversions: 270, engagement: 5.8 },
    createdAt: "2026-06-01T14:00:00Z",
    updatedAt: "2026-06-08T12:00:00Z",
  },
  {
    id: "asset-9",
    campaignId: "camp-5",
    title: "Customer Onboarding Email Drip",
    type: "email_campaign",
    channel: "email",
    aiScore: 94,
    status: "published",
    performance: { impressions: 32000, clicks: 4160, conversions: 832, engagement: 11.3 },
    createdAt: "2026-03-10T07:00:00Z",
    updatedAt: "2026-06-09T07:00:00Z",
  },
  {
    id: "asset-10",
    campaignId: "camp-5",
    title: "Case Study: Fortune 500 Deployment",
    type: "blog",
    channel: "content",
    aiScore: 90,
    status: "published",
    performance: { impressions: 15000, clicks: 2250, conversions: 450, engagement: 14.2 },
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-06-04T09:00:00Z",
  },
  {
    id: "asset-11",
    campaignId: "camp-6",
    title: "Google Ads Search Copy A/B Test",
    type: "ad_copy",
    channel: "search",
    aiScore: 87,
    status: "published",
    performance: { impressions: 320000, clicks: 48000, conversions: 1920, engagement: 4.5 },
    createdAt: "2026-05-15T06:00:00Z",
    updatedAt: "2026-06-08T18:00:00Z",
  },
  {
    id: "asset-12",
    campaignId: "camp-6",
    title: "Competitor Comparison Landing Page",
    type: "landing_page",
    channel: "search",
    aiScore: 93,
    status: "published",
    performance: { impressions: 68000, clicks: 10200, conversions: 816, engagement: 9.4 },
    createdAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-06-07T13:00:00Z",
  },
  {
    id: "asset-13",
    campaignId: "camp-7",
    title: "Webinar Registration Page",
    type: "landing_page",
    channel: "email",
    aiScore: 86,
    status: "review",
    performance: { impressions: 12000, clicks: 1800, conversions: 360, engagement: 8.7 },
    createdAt: "2026-06-01T11:00:00Z",
    updatedAt: "2026-06-08T10:00:00Z",
  },
  {
    id: "asset-14",
    campaignId: "camp-7",
    title: "Webinar Promo Social Carousel",
    type: "social_post",
    channel: "social",
    aiScore: 79,
    status: "draft",
    performance: { impressions: 0, clicks: 0, conversions: 0, engagement: 0 },
    createdAt: "2026-06-05T15:00:00Z",
    updatedAt: "2026-06-08T17:00:00Z",
  },
  {
    id: "asset-15",
    campaignId: "camp-8",
    title: "Re-engagement Winback Email",
    type: "email_campaign",
    channel: "email",
    aiScore: 96,
    status: "approved",
    performance: { impressions: 0, clicks: 0, conversions: 0, engagement: 0 },
    createdAt: "2026-06-07T08:00:00Z",
    updatedAt: "2026-06-09T06:00:00Z",
  },
];

export const attributionModels: AttributionModel[] = [
  {
    id: "attr-1",
    name: "Data-Driven Attribution",
    type: "data_driven",
    channels: [
      { channelId: "ch-search", attribution: 35 },
      { channelId: "ch-email", attribution: 25 },
      { channelId: "ch-social", attribution: 20 },
      { channelId: "ch-content", attribution: 12 },
      { channelId: "ch-display", attribution: 8 },
    ],
    accuracy: 94,
    privacySignals: {
      firstPartyCoverage: 87,
      serverSideEventCoverage: 91,
      modeledConversionShare: 31,
      consentedEventShare: 76,
      consentAuditTrailStatus: "complete",
      identityGraphMatchRate: 72,
      identityResolutionMode: "user_level",
      signalLossRisk: "low",
      validationMethod: "incrementality_test",
      incrementalityHoldoutShare: 12,
      incrementalityTestDesign: "geo_holdout",
      incrementalityReadoutWindowDays: 28,
      businessOutcomeKpi: "Qualified pipeline revenue",
      cookielessReady: true,
    },
  },
  {
    id: "attr-2",
    name: "Time Decay Model",
    type: "time_decay",
    channels: [
      { channelId: "ch-search", attribution: 40 },
      { channelId: "ch-email", attribution: 30 },
      { channelId: "ch-social", attribution: 15 },
      { channelId: "ch-content", attribution: 10 },
      { channelId: "ch-display", attribution: 5 },
    ],
    accuracy: 82,
    privacySignals: {
      firstPartyCoverage: 64,
      serverSideEventCoverage: 52,
      modeledConversionShare: 18,
      consentedEventShare: 58,
      consentAuditTrailStatus: "partial",
      identityGraphMatchRate: 58,
      identityResolutionMode: "user_level",
      signalLossRisk: "high",
      validationMethod: "platform_attribution",
      incrementalityHoldoutShare: null,
      incrementalityTestDesign: "none",
      incrementalityReadoutWindowDays: null,
      businessOutcomeKpi: "Attributed conversions",
      cookielessReady: false,
    },
  },
  {
    id: "attr-3",
    name: "Marketing Mix Model (MMM)",
    type: "marketing_mix",
    channels: [
      { channelId: "ch-search", attribution: 30 },
      { channelId: "ch-email", attribution: 28 },
      { channelId: "ch-social", attribution: 22 },
      { channelId: "ch-content", attribution: 14 },
      { channelId: "ch-display", attribution: 6 },
    ],
    accuracy: 89,
    privacySignals: {
      firstPartyCoverage: 96,
      serverSideEventCoverage: 98,
      modeledConversionShare: 0,
      consentedEventShare: 94,
      consentAuditTrailStatus: "complete",
      identityGraphMatchRate: null,
      identityResolutionMode: "aggregate_mmm",
      signalLossRisk: "low",
      validationMethod: "marketing_mix_model",
      incrementalityHoldoutShare: null,
      incrementalityTestDesign: "none",
      incrementalityReadoutWindowDays: null,
      businessOutcomeKpi: "Incremental revenue contribution",
      cookielessReady: true,
    },
  },
];

export const aiGeneratedContent: AIGeneratedContent[] = [
  {
    id: "ai-1",
    campaignId: "camp-1",
    title: "AI: Q4 Product Feature Announcement",
    type: "blog",
    channel: "content",
    preview: "Introducing our most powerful analytics suite yet. Real-time dashboards, predictive insights, and AI-powered recommendations -- all in one unified platform. Early adopters report 3x faster decision cycles...",
    score: 91,
    keywords: ["analytics", "AI", "real-time", "predictive", "dashboard"],
    sentiment: "persuasive",
    generatedAt: "2026-06-09T09:00:00Z",
  },
  {
    id: "ai-2",
    campaignId: "camp-2",
    title: "AI: Flash Sale Email Subject Lines",
    type: "email_campaign",
    channel: "email",
    preview: "Subject: Your exclusive 48-hour offer expires tonight | Body: We've curated a selection of best-sellers just for you. 30-50% off with code SUMMER30. Free shipping on orders $75+...",
    score: 88,
    keywords: ["flash sale", "exclusive", "limited time", "discount"],
    sentiment: "persuasive",
    generatedAt: "2026-06-09T08:30:00Z",
  },
  {
    id: "ai-3",
    campaignId: "camp-4",
    title: "AI: Holiday Shopping Guide Ad Copy",
    type: "ad_copy",
    channel: "search",
    preview: "Headline: The Ultimate 2026 Holiday Gift Guide | Description: Hand-picked gifts for everyone on your list. Compare prices, read reviews, and get it delivered in 2 days. Shop now...",
    score: 84,
    keywords: ["holiday", "gift guide", "shopping", "deals", "fast delivery"],
    sentiment: "positive",
    generatedAt: "2026-06-09T07:45:00Z",
  },
  {
    id: "ai-4",
    campaignId: "camp-5",
    title: "AI: Customer Success Story Video Script",
    type: "video_script",
    channel: "social",
    preview: "[0:00] Hook: 'They said enterprise AI was too complex. We proved them wrong.' [0:15] Problem: Fortune 500 retailer struggling with inventory forecasting [0:45] Solution: Our platform reduced stockouts by 67%...",
    score: 93,
    keywords: ["success story", "enterprise", "AI", "ROI", "case study"],
    sentiment: "persuasive",
    generatedAt: "2026-06-09T09:15:00Z",
  },
  {
    id: "ai-5",
    campaignId: "camp-6",
    title: "AI: Competitor Battle Card Landing Page",
    type: "landing_page",
    channel: "search",
    preview: "Hero: Why teams switch to us (and never look back). Feature comparison table: 14 categories, side-by-side. Testimonial carousel: 8 verified CTO reviews. Bottom CTA: Start free trial...",
    score: 89,
    keywords: ["comparison", "vs", "alternative", "switch", "better"],
    sentiment: "neutral",
    generatedAt: "2026-06-09T08:00:00Z",
  },
];

export const campaigns: Campaign[] = [
  {
    id: "camp-1",
    name: "Q3 Product Launch",
    description: "Multi-channel launch campaign for the new AI Analytics Suite targeting enterprise decision-makers",
    status: "active",
    goal: "conversion",
    channels: [channels[2], channels[3], channels[0]],
    contentAssets: [contentAssets[0], contentAssets[1]],
    budget: 250000,
    spend: 218400,
    revenue: 873600,
    roas: 4.0,
    conversionRate: 3.8,
    impressions: 3250000,
    clicks: 189500,
    startDate: "2026-05-01",
    endDate: "2026-08-31",
    createdAt: "2026-04-15T08:00:00Z",
    updatedAt: "2026-06-09T09:00:00Z",
  },
  {
    id: "camp-2",
    name: "Summer Promotional Blitz",
    description: "Seasonal promotion across email and display channels driving e-commerce sales",
    status: "active",
    goal: "conversion",
    channels: [channels[0], channels[3]],
    contentAssets: [contentAssets[2], contentAssets[3]],
    budget: 120000,
    spend: 103500,
    revenue: 310500,
    roas: 3.0,
    conversionRate: 5.2,
    impressions: 4600000,
    clicks: 215000,
    startDate: "2026-06-01",
    endDate: "2026-08-31",
    createdAt: "2026-05-20T10:00:00Z",
    updatedAt: "2026-06-09T08:00:00Z",
  },
  {
    id: "camp-3",
    name: "Enterprise Thought Leadership",
    description: "Content-driven brand awareness campaign targeting C-suite executives in Fortune 1000",
    status: "active",
    goal: "awareness",
    channels: [channels[4], channels[1]],
    contentAssets: [contentAssets[4], contentAssets[5]],
    budget: 95000,
    spend: 87200,
    revenue: 348800,
    roas: 4.0,
    conversionRate: 2.1,
    impressions: 2100000,
    clicks: 135000,
    startDate: "2026-04-01",
    endDate: "2026-09-30",
    createdAt: "2026-03-15T09:00:00Z",
    updatedAt: "2026-06-09T07:30:00Z",
  },
  {
    id: "camp-4",
    name: "Holiday Season 2026",
    description: "Pre-holiday campaign building early momentum for Q4 retail push with content and social",
    status: "active",
    goal: "awareness",
    channels: [channels[4], channels[1]],
    contentAssets: [contentAssets[6], contentAssets[7]],
    budget: 180000,
    spend: 82100,
    revenue: 205250,
    roas: 2.5,
    conversionRate: 1.8,
    impressions: 5800000,
    clicks: 290000,
    startDate: "2026-05-25",
    endDate: "2026-12-31",
    createdAt: "2026-05-10T12:00:00Z",
    updatedAt: "2026-06-08T15:00:00Z",
  },
  {
    id: "camp-5",
    name: "Customer Retention Program",
    description: "Email and content-driven retention campaign reducing churn and increasing LTV for existing accounts",
    status: "active",
    goal: "retention",
    channels: [channels[0], channels[4]],
    contentAssets: [contentAssets[8], contentAssets[9]],
    budget: 65000,
    spend: 58400,
    revenue: 292000,
    roas: 5.0,
    conversionRate: 8.5,
    impressions: 950000,
    clicks: 85500,
    startDate: "2026-03-01",
    createdAt: "2026-02-15T08:00:00Z",
    updatedAt: "2026-06-09T06:00:00Z",
  },
  {
    id: "camp-6",
    name: "Competitive Takeover Campaign",
    description: "Aggressive paid search and landing page optimization targeting competitor brand keywords",
    status: "active",
    goal: "conversion",
    channels: [channels[2]],
    contentAssets: [contentAssets[10], contentAssets[11]],
    budget: 165000,
    spend: 152800,
    revenue: 534800,
    roas: 3.5,
    conversionRate: 4.2,
    impressions: 5100000,
    clicks: 280000,
    startDate: "2026-05-15",
    createdAt: "2026-05-01T10:00:00Z",
    updatedAt: "2026-06-09T05:00:00Z",
  },
  {
    id: "camp-7",
    name: "Webinar Lead Generation",
    description: "Lead gen campaign driving registrations for the quarterly AI Trends webinar series",
    status: "active",
    goal: "lead_gen",
    channels: [channels[0], channels[1]],
    contentAssets: [contentAssets[12], contentAssets[13]],
    budget: 45000,
    spend: 32400,
    revenue: 97200,
    roas: 3.0,
    conversionRate: 12.0,
    impressions: 680000,
    clicks: 47500,
    startDate: "2026-06-01",
    endDate: "2026-07-15",
    createdAt: "2026-05-25T14:00:00Z",
    updatedAt: "2026-06-08T17:00:00Z",
  },
  {
    id: "camp-8",
    name: "Winback & Reactivation",
    description: "Targeted email sequence re-engaging dormant users with personalized offers and AI recommendations",
    status: "active",
    goal: "retention",
    channels: [channels[0]],
    contentAssets: [contentAssets[14]],
    budget: 35000,
    spend: 12400,
    revenue: 62000,
    roas: 5.0,
    conversionRate: 7.8,
    impressions: 320000,
    clicks: 48000,
    startDate: "2026-06-07",
    createdAt: "2026-06-01T09:00:00Z",
    updatedAt: "2026-06-09T06:00:00Z",
  },
];

export function computeMetrics(): MarketingMetrics {
  const activeCampaigns = campaigns.filter((c) => c.status === "active").length;
  const totalBudget = campaigns.reduce((s, c) => s + c.budget, 0);
  const totalSpend = campaigns.reduce((s, c) => s + c.spend, 0);
  const totalRevenue = campaigns.reduce((s, c) => s + c.revenue, 0);
  const overallROAS = totalSpend > 0 ? Math.round((totalRevenue / totalSpend) * 10) / 10 : 0;
  const avgConversionRate =
    campaigns.length > 0
      ? Math.round((campaigns.reduce((s, c) => s + c.conversionRate, 0) / campaigns.length) * 10) / 10
      : 0;
  const totalImpressions = campaigns.reduce((s, c) => s + c.impressions, 0);
  const totalClicks = campaigns.reduce((s, c) => s + c.clicks, 0);

  const channelMap = new Map<string, { revenue: number; roas: number; spend: number }>();
  for (const ch of channels) {
    channelMap.set(ch.type, { revenue: ch.revenue, roas: ch.roas, spend: ch.spend });
  }
  const channelBreakdown = ["email", "social", "search", "display", "content"].map((ct) => {
    const d = channelMap.get(ct);
    return { channel: ct as Channel["type"], revenue: d?.revenue ?? 0, roas: d?.roas ?? 0, spend: d?.spend ?? 0 };
  });

  const topAsset = [...contentAssets].sort((a, b) => b.aiScore - a.aiScore)[0];

  return {
    totalCampaigns: campaigns.length,
    activeCampaigns,
    totalBudget,
    totalSpend,
    totalRevenue,
    overallROAS,
    avgConversionRate,
    totalImpressions,
    totalClicks,
    channelBreakdown,
    topPerformingAsset: topAsset?.title ?? "N/A",
    aiContentGenerated: aiGeneratedContent.length,
  };
}
